# Generated by Django 4.2 on 2023-04-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to='media/blog'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='media/service'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='image',
            field=models.ImageField(upload_to='media/team'),
        ),
    ]
