# Generated by Django 4.2 on 2023-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_blogs_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
